name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          sh ./build.sh

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
